# General configuration
project_name: "tumor_prediction_model"

# Data settings
data:
  gene_fusions: "data/Lung/20231023_092657_fusions_latest.csv"
  copy_number_variation: "data/Lung/20231023_092657_imputed_copynumber.csv"
  drug_response: "data/Lung/20231023_092657_imputed_drugresponse.csv"
  metabolomics: "data/Lung/20231023_092657_imputed_metabolomics.csv"
  methylation: "data/Lung/20231023_092657_imputed_methylation.csv"
  proteomics: "data/Lung/20231023_092657_imputed_proteomics.csv"
  transcriptomics: "data/Lung/20231023_092657_imputed_transcriptomics.csv"
  crisprcas9: "data/Lung/20231023_092657_imputed_crisprcas9.csv"

preprocessing:
  top_features: 50
  augmentation_factor: 3

random_seed: 1

outcome_name: "proteomics"

models:
  linear_regression:
    names: ['drug_response', 'crisprcas9', 'metabolomics', 'transcriptomics', 'copy_number_variation', 'methylation']

  self_attention:
    names: ['drug_response', 'crisprcas9', 'metabolomics', 'transcriptomics', 'copy_number_variation', 'methylation']
    d_model: 8
    num_heads: 4
    key_dim: 8
    training:
      batch_size: 2
      epochs: 150
      learning_rate: 0.001
      patience: 10
      validation_split: 0.2

  cross_attention:
    self_attention_names: ['drug_response', 'crisprcas9', 'metabolomics']
    cross_attention_names: ['transcriptomics', 'copy_number_variation', 'methylation']
    d_model: 8
    num_heads: 4
    key_dim: 8
    training:
      batch_size: 2
      epochs: 200
      learning_rate: 0.001
      patience: 10
      validation_split: 0.2

  rnn:
    names: ['drug_response', 'crisprcas9', 'metabolomics', 'transcriptomics', 'copy_number_variation', 'methylation']
    lstm_units: 64
    training:
      batch_size: 32
      epochs: 300
      learning_rate: 0.001
      patience: 10
      validation_split: 0.2

cross_validation:
  n_folds: 2
